config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users, controllers: {omniauth_callbacks: 'users/omniauth_callbacks'}
  get '/user', to: redirect('/routes')
  resources :routes 
  resources :regions
  resources :countries
  root 'routes#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/country.rb
class Country < ApplicationRecord
end

app/models/region.rb
class Region < ApplicationRecord
  belongs_to :country
end

app/models/route.rb
class Route < ApplicationRecord
  belongs_to :country
  belongs_to :region
  belongs_to :user

  enum grade: [:"5-", :"5+", :"6a", :"6a+", :"6b", :"6b+", :"6c", :"6c+", :"7a", :"7a+", :"7b", :"7b+", :"7c", :"7c+", :"8a", :"8a+", :"8b", :"8b+", :"8c", :"8c+", :"9a", :"9a+", :"9b", :"9b+", :"9c", :"9c+"]

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: [:google_oauth2]

  has_many :routes
  def self.from_omniauth(access_token)
    data = access_token.info
    user = User.where(email: data['email']).first
     unless user
         user = User.create(
            email: data['email'],
            password: Devise.friendly_token[0,20]
         )
     end
    user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    protect_from_forgery with: :exception

    before_action :configure_permitted_parameters, if: :devise_controller?

    protected

         def configure_permitted_parameters
              devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :lastname, :email, :password)}

              devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :lastname, :email, :password, :current_password)}
         end
end

app/controllers/countries_controller.rb
class CountriesController < InheritedResources::Base

  private

    def country_params
      params.require(:country).permit(:name)
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/regions_controller.rb
class RegionsController < InheritedResources::Base

  private

    def region_params
      params.require(:region).permit(:name, :country_id)
    end

end

app/controllers/routes_controller.rb
class RoutesController < InheritedResources::Base
  before_action :authenticate_user!, except: [:index]

  def index 
    @route = Route.new
    @routes = Route.order("created_at DESC")
  end

  def create
    @route = Route.new(route_params)
    @route.user = current_user
    puts @route
    puts @route.name
    respond_to do |format|
      if @route.save
        @route_new = Route.new
        format.html { redirect_to route_url(@route), notice: "Route was successfully created." }
        format.json { render :show, status: :created, location: @route }
        format.js
        format.turbo_stream
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @route.errors, status: :unprocessable_entity }
        format.js
        format.turbo_stream
      end
    end
  end

  private

    def route_params
      params.require(:route).permit(:country_id, :region_id, :location, :zone, :name, :grade, :date, :category, :lead_climbing, :observation)
    end

end

app/controllers/users/omniauth_callbacks_controller.rb
# app/controllers/users/omniauth_callbacks_controller.rb:

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

    def google_oauth2
        handle_auth "Google"
    end

    def github
        handle_auth "Github"
    end

    def handle_auth(kind)
        # You need to implement the method below in your model (e.g. app/models/user.rb)
        @user = User.from_omniauth(request.env['omniauth.auth'])
  
        if @user.persisted?
          flash[:notice] = I18n.t 'devise.omniauth_callbacks.success', kind: kind
          sign_in_and_redirect @user, event: :authentication
        else
          session['devise.auth_data'] = request.env['omniauth.auth'].except('extra') # Removing extra as it can overflow some session stores
          redirect_to new_user_registration_url, alert: @user.errors.full_messages.join("\n")
        end
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/regions_helper.rb
module RegionsHelper
end

app/helpers/routes_helper.rb
module RoutesHelper
end

app/views/countries/_country.html.erb
<div id="<%= dom_id country %>">
  <p class="box">
    <strong>Name:</strong>
    <%= country.name %>
  </p>

</div>

app/views/countries/_form.html.erb
<%= form_with(model: country) do |form| %>
  <% if country.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(country.errors.count, "error") %> prohibited this country from being saved:</h2>

      <ul>
        <% country.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/countries/edit.html.erb
<h1>Editing country</h1>

<%= render "form", country: @country %>

<br>

<div>
  <%= link_to "Show this country", @country %> |
  <%= link_to "Back to countries", countries_path %>
</div>

app/views/countries/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Countries</h1>
<br>
<div id="countries" class="columns is-mobile">
  <% @countries.each do |country| %>
    <div class="card">
      <div class="card-content"%>
        <%= render country %>
        <p>
          <%= link_to "Show this country", country, class:"button is-link is-light"%>
        </p>
      </div>
    </div>
  <% end %>
</div>

<%= link_to "New country", new_country_path %>

app/views/countries/new.html.erb
<h1>New country</h1>

<%= render "form", country: @country %>

<br>

<div>
  <%= link_to "Back to countries", countries_path %>
</div>

app/views/countries/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @country %>

<div>
  <%= link_to "Edit this country", edit_country_path(@country) %> |
  <%= link_to "Back to countries", countries_path %>

  <%= button_to "Destroy this country", @country, method: :delete %>
</div>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LuMiAppv1</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css">
    <script src="https://cdn.jsdelivr.net/npm/bulma-carousel@3.0.0/dist/js/bulma-carousel.min.js"></script>
    <script src="//code.jquery.com/jquery-3.3.1.min.js"></script>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= render 'shared/navbar' %>
    <%= render 'shared/hero' %>
    <div data-controller="hello">
     
    </div>

      <%= yield %>

  </body>
  <script type="text/javascript" src="http://code.jquery.com/jquery-latest.min.js"></script>
  <script src="//code.jquery.com/jquery-3.3.1.min.js"></script>
</html>

app/views/regions/_form.html.erb
<%= form_with(model: region) do |form| %>
  <% if region.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(region.errors.count, "error") %> prohibited this region from being saved:</h2>

      <ul>
        <% region.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :country_id, style: "display: block" %>
    <%= form.select :country_id, Country.pluck(:name, :id), class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>
  
  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/regions/_region.html.erb
<div id="<%= dom_id region %>">
  <p>
    <strong>Name:</strong>
    <%= region.name %>
  </p>

  <p>
    <strong>Country:</strong>
    <%= region.country_id %>
  </p>

</div>

app/views/regions/edit.html.erb
<h1>Editing region</h1>

<%= render "form", region: @region %>

<br>

<div>
  <%= link_to "Show this region", @region %> |
  <%= link_to "Back to regions", regions_path %>
</div>

app/views/regions/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Regions</h1>

<br>
<div id="regions" class="columns is-mobile">
  <% @regions.each do |region| %>
    <div class="card">
      <div class="card-content"%>
        <%= render region%>
        <p>
          <%= link_to "Show this country", region, class:"button is-link is-light"%>
        </p>
      </div>
    </div>
  <% end %>
</div>

<%= link_to "New region", new_region_path %>

app/views/regions/new.html.erb
<h1>New region</h1>

<%= render "form", region: @region %>

<br>

<div>
  <%= link_to "Back to regions", regions_path %>
</div>

app/views/regions/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @region %>

<div>
  <%= link_to "Edit this region", edit_region_path(@region) %> |
  <%= link_to "Back to regions", regions_path %>

  <%= button_to "Destroy this region", @region, method: :delete %>
</div>

app/views/routes/_form.html.erb
<%= form_with(model: route, remote: true) do |form| %>
  <% if route.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(route.errors.count, "error") %> prohibited this route from being saved:</h2>

      <ul>
        <% route.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <div class="columns">

    <div class="column ">
      <h1 class="title">Estos campos son obligatorios</h1>
      <div>
        <%= form.label :location, style: "display: block" %>
        <%= form.text_field :location %>
      </div>

      <div>
        <%= form.label :zone, style: "display: block" %>
        <%= form.text_field :zone %>
      </div>

      <div>
        <%= form.label :name, style: "display: block" %>
        <%= form.text_field :name %>
      </div>

      <div>
        <%= form.label :grade, style: "display: block" %>
<%= select_tag :grades, options_for_select(Route.grades) %>

      </div>

      <div>
        <%= form.label :date, style: "display: block" %>
        <%= form.date_field :date %>
      </div>

    </div>

    <div class="column">
      <h1 class="title">Estos campos NO son obligatorios</h1>
      <div>
        <%= form.label :category, style: "display: block" %>
        <%= form.number_field :category %>
      </div>

      <div>
        <%= form.label :lead_climbing, style: "display: block" %>
        <%= form.text_field :lead_climbing %>
      </div>

      <div>
        <%= form.label :observation, style: "display: block" %>
        <%= form.text_field :observation %>
      </div>

      <div>
        <%= form.label :country_id, style: "display: block" %>
        <%= form.select :country_id, Country.pluck(:name, :id), class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
      </div>

      <div>
        <%= form.label :region_id, style: "display: block" %>
        <%= form.select :region_id, Region.pluck(:name, :id), class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
      </div>
    </div>


  </div>

<br>
  <div>
    <%= form.submit class:"button is-dark" %>
  </div>
<% end %>

app/views/routes/_route.html.erb
<div id="<%= dom_id route %>" class="column is-6">
  <br>
    <div class="card">
      <div class="card-content">
        <div class="media">
          <div class="media-content">
          <%if route.user != nil%>
          <%#unless route.user.nil?%>
            <div class="button is-primary is-light">
              <%= route.user.name%>  <%= route.user.lastname%>
            </div>
            <div>
              <%= route.date%>
            </div>
          <%end%>
          </div>
        </div>
          <div class="container">
            <div class="columns">
              <div class="column">
                <p>Ubicacion</p>
                <p>Ruta</p>
                <p>Grado</p>
                

              </div>
              <div class="column">
                <p><%= route.location %></p>
                <p><%= route.name %></p>
                <p><%= route.grade %></p>
              </div>
            </div>
            <%= link_to "Mostrar Ruta", route, class:"button is-link is-light"%>
          </div>
      </div>
    </div>
  <br>
</div>

app/views/routes/create.js.erb
console.log('Hola')

app/views/routes/edit.html.erb
<h1>Editing route</h1>

<%= render "form", route: @route %>

<br>

<div>
  <%= link_to "Show this route", @route %> |
  <%= link_to "Back to routes", routes_path %>
</div>

app/views/routes/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Routes asdasd</h1>
<%= Rails.env%>

<div class="container has-text-centered"> 
  <div id="routes">
    <%= render "form", route: @route%>
  </div>
 <br>
  <div id="routes" class=" content columns is-multiline">
    <% @routes.each do |route|%>
      <%= render route %>
    <% end %>
  </div>
    

</div>

<%#= link_to "New route", new_route_path %>

app/views/routes/new.html.erb
<h1>New route</h1>

<%= render "form", route: @route %>

<br>

<div>
  <%= link_to "Back to routes", routes_path %>
</div>

app/views/routes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @route %>

<div>
  <%= link_to "Edit this route", edit_route_path(@route) %> |
  <%= link_to "Back to routes", routes_path %>

  <%= button_to "Destroy this route", @route, method: :delete %>
</div>

app/views/shared/_hero.html.erb
<section class="hero is-large is-info" style="background-image: url('https://hdsports.cl/wp-content/uploads/2018/05/fareescalada1.jpg')">
  <div class="hero-body">
    <p class="title">
      ¡Bienvenidos a LuMi!
    </p>
    <p class="subtitle">
      Plataforma creada para que escaladores puedan mostrar sus rutas finalizadas
    </p>
  </div>
</section>

app/views/shared/_navbar.html.erb
<nav class="navbar" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <%= link_to 'Inicio', root_path, class: "navbar-item"%>
    <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navbarBasicExample" class="navbar-menu ">
    <div class="navbar-start">
        <%= link_to 'Dashboard', root_path, class: "navbar-item"%>

      <div class="navbar-item has-dropdown is-hoverable">
        <a class="navbar-link">
          More
        </a>

        <div class="navbar-dropdown">
        <%= link_to 'Pais', countries_path, class: "navbar-item"%>
        <%= link_to 'Regiones', regions_path, class: "navbar-item"%>
        <%= link_to 'Rutas', routes_path, class: "navbar-item"%>
        </div>
      </div>
    </div>

    <div class="navbar-end">
      <div class="navbar-item">
        <div class="buttons">
            <% if user_signed_in? %>
              <%= link_to  "Hola #{current_user.name}", edit_user_registration_path, class:"button is-light"%>
              <%= link_to "Log out", destroy_user_session_path, "data-turbo-method"=>'delete', class:"button is-primary"%>
              
            <% else %>
                <%= link_to 'Soy nuevo!', new_user_registration_path, class:"button is-light"%>
                <%= link_to "Login", new_user_session_path, class:"button is-primary" %>
            <% end %>
        </div>
      </div>
    </div>
  </div>
</nav>